# Generated by Django 4.1 on 2022-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('region', models.CharField(choices=[('novosib', 'Новосибирская область'), ('barnaul', 'Алтайский край'), ('omsk', 'Омская область'), ('tomsk', 'Томская область'), ('kemerovo', 'Кемеровская область'), ('krasnoyarsk', 'Красноярский край'), ('irkutsk', 'Иркутская область'), ('chita', 'Забайкальский край'), ('tyva', 'Республика Тыва'), ('buratia', 'Республика Бурятия'), ('altai', 'Республика Алтай'), ('khakasia', 'Республика Хакасия')], max_length=20)),
                ('sick', models.IntegerField()),
                ('died', models.IntegerField()),
                ('sick_today', models.IntegerField()),
                ('died_today', models.IntegerField()),
            ],
        ),
    ]
